services:
  db:
    container_name: immudb
    image: codenotary/immudb:latest
    networks:
      - vpn
    ports:
      - 3322:3322
      - 9497:9497
  backend:
    container_name: trpc
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - vpn
    ports:
      - 7070:7070
    depends_on:
      - db
    volumes:
      - ./server/src:/home/server/src
      - ./server/package.json:/home/server/package.json
      - ./server/pnpm-lock.yaml:/home/server/pnpm-lock.yaml
      - ./server/vitest.config.ts:/home/server/vitest.config.ts
      - ./server/tsconfig.json:/home/server/tsconfig.ts
      - ./server/.prettierrc:/home/server/.prettierrc
      - ./server/.eslintrc.cjs:/home/server/.eslintrc.cjs
    env_file:
      - .env
  client:
    container_name: trpc-fe
    image: node:22-alpine
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  vpn:
    name: vpn
    driver: bridge
