import createClient from 'openapi-fetch';
import { config } from '~/config';

import type { paths } from '../types/immudb-vault-types'; // generated by openapi-typescript

export const immudbVaultClient = createClient<paths>({
  baseUrl: 'https://vault.immudb.io/ics/api/v1/',
  headers: {
    'X-API-Key': config.IMMUDB_VAULT_TOKEN,
  },
});
