import createClient, { Middleware } from 'openapi-fetch';
import { config } from '~/config';

import type { paths } from '../types/immudb-vault-types'; // generated by openapi-typescript

const authMiddleware: Middleware = {
  onRequest({ request }) {
    request.headers.set('X-API-Key', config.IMMUDB_VAULT_TOKEN);
    return request;
  },
};

const immudbVaultClient = createClient<paths>({
  baseUrl: config.IMMUDB_VAULT_URL,
});

immudbVaultClient.use(authMiddleware);

export { immudbVaultClient };
